[package]
name = "staking"
version = "1.10.6"
edition = "2023_11"

[dependencies]
starknet.workspace = true
openzeppelin.workspace = true
contracts_commons.workspace = true

[dev-dependencies]
assert_macros.workspace = true
snforge_std.workspace = true

[scripts]
test = "SNFORGE_BACKTRACE=1 snforge test"

[lib]

[[target.starknet-contract]]

[[test]]
name = "contracts_unittest"
build-external-contracts = ["contracts_commons::erc20_mocks::DualCaseERC20Mock"]

[tool.fmt]
sort-module-level-items = true

[tool]
snforge.workspace = true
